# Generated by Django 3.0.2 on 2020-01-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('review_title', models.CharField(blank=True, max_length=100)),
                ('review_rating', models.IntegerField(blank=True, null=True)),
                ('review_content', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
